
[default_profile]
cfg_dir = "/home/mepholic/.config/awesome/"
theme_dir = "powerarrowf/"
theme_script = "theme.lua"
panel_font = "Noto Mono"
panel_size = "16"
panel_pos = "top"
titlebars = false
browser = "google-chrome"
editor = "emacs"
terminal = "urxvt256c"
batt_name = ""
fs_mon = "/home"
if_wired = "eth0"
if_wlan = ""
alsa_name = "Master"
tags = [ [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] ]
wallpaper = [ "/home/mepholic/.config/awesome/res/candy_bean_wallpaper.jpg" ]
xrandr_cfg = false
xrandr_pri = false

[profiles]

[profiles.cataclysm]
terminal = "urxvt"
fs_mon = "/"
if_wlan = "wlan0"
batt_name = "BAT1"
tags = [ [ "term", "web", "chat", "mail", "misc", "misc", "music" ], ["term", "aux1", "aux2", "aux3"] ]
wallpaper = [ "/home/mepholic/.config/awesome/res/club_aurigia.jpg" ]
awful_rules = false

#[[profiles.chronos.awful_rules]]
#	[[profiles.chronos.awful_rules.rule_all]]
#	class = [ "urxvt" ]
#	[[profiles.chronos.awful_rules.loc]]
#	tag = 1

[theme]
font           = "Noto Mono 12"

bg_normal      = "#222222"
bg_focus       = "#1E2320"
bg_urgent      = "#BC717A"
bg_systray     = "#222222"

fg_normal      = "#AAAAAA"
fg_focus       = "#0099CC"
fg_urgent      = "#3F3F3F"

border_width   = 1
border_normal  = "#000000"
border_focus   = "#535d6c"
border_marked  = "#91231c"
